server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:users
  application:
    name: users
  profiles:
    active: memory
  cloud:
    stream:
      bindings:
        output:
          destination: aish
          contentType: text/plain
        # uncomment below to use the last digit of the seconds as a partition key
        # hashcode(key) % N is then applied with N being the partitionCount value
        # thus, even seconds should go to the 0 queue, odd seconds to the 1 queue
        #producerProperties:
        #  partitionKeyExpression: payload.charAt(payload.length()-1)
        #  partitionCount: 2
